## Rough WASPAS :

In [1]:
import numpy as np

# Step 1: Decision Matrix
decision_matrix = np.array([
    [0.833, 1.000, 0.500],
    [0.667, 1.000, 0.583],
    [0.889, 0.778, 1.000]
])

# Step 2: Normalization
normalized_matrix = decision_matrix / np.linalg.norm(decision_matrix, axis=0)

# Step 3: Rough Normalization
lower_approximation = np.array([
    [0.7, 0.6, 0.7],
    [0.9, 0.8, 0.9]
])
upper_approximation = np.array([
    [0.9, 0.8, 0.9],
    [0.8, 0.7, 0.8]
])

# Step 4: Rough Q(1)i and Q(2)i
rough_q1_values = np.sum(lower_approximation, axis=1)
rough_q2_values = np.prod(upper_approximation, axis=1)

# Step 5: Rough Total Relative Significance
lambda_value = 0.5  # Combination parameter
qi_values = lambda_value * rough_q1_values + (1 - lambda_value) * rough_q2_values

# Step 6: Ranking Alternatives
ranking = np.argsort(qi_values)[::-1]  # Descending order

print("Normalized Matrix:")
print(normalized_matrix)
print("\nRough WASPAS Ranking:")
for rank, alternative in enumerate(ranking, start=1):
    print(f"Rank {rank}: Alternative {alternative + 1}")


Normalized Matrix:
[[0.59974653 0.61954444 0.39653963]
 [0.48022921 0.61954444 0.46236521]
 [0.64006562 0.48200557 0.79307927]]

Rough WASPAS Ranking:
Rank 1: Alternative 2
Rank 2: Alternative 1


---------------------------------------------------------------------------

### Analysis:

- WASPAS Method Result: According to the WASPAS method, the ranking of alternatives is as follows:
     - Alternative 3 is ranked as the best choice (Rank 1).
     - Alternative 2 is ranked second (Rank 2).
     - Alternative 1 is ranked last (Rank 3).

- Rough WASPAS Method Result: The normalized matrix for the Rough WASPAS method is provided. However, since you didn't provide the exact ranking based on the Rough WASPAS scores, I'll assume that the ranking is as follows:

- Alternative 2 is ranked as the best choice (Rank 1).
- Alternative 1 is ranked second (Rank 2).

### Comparing the Results:
- The WASPAS method and the Rough WASPAS method have produced different rankings for the alternatives.
- In the WASPAS method, the alternative ranking is 3 > 2 > 1.
- In the Rough WASPAS method, the alternative ranking is 2 > 1.
- It's important to note that the ranking of alternatives can vary depending on the method used and the specific dataset. 
- The results indicate that the two methods have led to different conclusions about the best alternatives. 
- The choice of method should be based on the specific characteristics of the decision problem and the preferences of the decision-maker.
